# Generated by Django 5.1.6 on 2025-04-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0002_collection_is_private_patron_custom_username_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collection',
        #     name='is_private',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='patron',
        #     name='s3_profile_picture_key',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        migrations.AlterField(
            model_name='patron',
            name='custom_username',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
