# Generated by Django 4.2.18 on 2025-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0002_alter_collection_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
