# Generated by Django 4.2.18 on 2025-03-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0003_collection_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'librarian'), (2, 'patron'), (3, 'anonymous')], default=2),
        ),
    ]
