# Generated by Django 5.1.6 on 2025-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0003_collection_is_private_patron_s3_profile_picture_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allowed_patrons',
            field=models.ManyToManyField(blank=True, related_name='allowed_collections', to='clothing_lending.patron'),
        ),
    ]
