# Generated by Django 5.1.6 on 2025-04-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0004_collection_allowed_patrons_collection_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='private_collection',
            field=models.BooleanField(default=False),
        ),
    ]
