# Generated by Django 5.1.6 on 2025-03-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0002_remove_user_custom_username_and_more'),
        ('clothing_lending', '0005_alter_user_user_type'),
    ]

    operations = [
    ]
