# Generated by Django 5.2 on 2025-04-27 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
