# Generated by Django 5.1.6 on 2025-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0008_category_remove_item_category_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
            preserve_default=False,
        ),
    ]
