# Generated by Django 5.2 on 2025-04-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0009_rating_rate_date'),
        ('clothing_lending', '0010_category_item_categories'),
    ]

    operations = [
    ]
