# Generated by Django 5.2 on 2025-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0011_merge_20250429_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='return_date',
        ),
        migrations.AddField(
            model_name='lending',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
