# Generated by Django 5.2 on 2025-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0012_remove_invite_return_date_lending_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNING', 'Return Requested'), ('RETURNED', 'Returned')], default='PENDING', max_length=10),
        ),
    ]
