# Generated by Django 5.2 on 2025-04-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0014_lending_return_requsted_alter_lending_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='return_requsted',
            new_name='return_requested',
        ),
    ]
