# Generated by Django 5.2 on 2025-04-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_lending', '0016_collection_example_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='example_field',
        ),
    ]
